dist: xenial
sudo: required
language: generic

branches:
    - master

before_install:
    - sudo apt-get update -y

install:
    - sudo apt-get install -y xmlstarlet

script:
    - make -k -C ./tools/work test validate
