dist: bionic
sudo: required
language: generic

branches:
    - master

before_install:
    - sudo apt-get update -y

install:
    - sudo apt install -y xmlstarlet grep

script:
    - make -k -C ./tools/work test validate
